### PR TITLE
Rename repository to project

### PR DESCRIPTION
**Pull request by MoritzWeber0**
Small addition to #229.

### CODE REVIEW

**Comment by TimoBbz** [comment]
There are some left there: https://github.com/DSD-DBS/capella-collab-manager/blob/v2/rename-repos/backend/capellacollab/core/authentication/database/jenkins.py#L13
Also there but the used function doesn’t exist anymore: https://github.com/DSD-DBS/capella-collab-manager/blob/v2/rename-repos/backend/capellacollab/extensions/backups/ease/routes.py#L66

**Comment by MoritzWeber0** [comment]
> There are some left there: https://github.com/DSD-DBS/capella-collab-manager/blob/v2/rename-repos/backend/capellacollab/core/authentication/database/jenkins.py#L13 

Thanks. The file is not used anymore. I deleted it. 

> Also there but the used function doesn’t exist anymore: https://github.com/DSD-DBS/capella-collab-manager/blob/v2/rename-repos/backend/capellacollab/extensions/backups/ease/routes.py#L66 

The code segment is not used anymore, but will be used when introducing backups again. I'll fix it in the separate PR when the functionality comes back.

> Finally, a lot of leftover references there: https://github.com/DSD-DBS/capella-collab-manager/blob/v2/rename-repos/backend/capellacollab/projects/users/routes.py

I missed these references. I'll fix it right away.

**Comment by TimoBbz** [comment]
Some left there also: https://github.com/DSD-DBS/capella-collab-manager/blob/v2/rename-repos/backend/capellacollab/sessions/routes.py#L145
And globally in the functions of the `session` module. I don’t raise those of `extensions.modelsources.t4c` because I’m currently working on it.

**Comment by MoritzWeber0** [comment]
> Some left there also: https://github.com/DSD-DBS/capella-collab-manager/blob/v2/rename-repos/backend/capellacollab/sessions/routes.py#L145 And globally in the functions of the `session` module. I don’t raise those of `extensions.modelsources.t4c` because I’m currently working on it.

I left out `sessions` explicitly because Arjan worked on it.

**Comment by MoritzWeber0** [comment]
I just improved two other small things as I don't wanted to create new PR for them. You may want to check it.

**Review by TimoBbz — APPROVED** [review]

**Pull request merged**
