### PR TITLE
feat: Improve readability of log messages

### PR DESCRIPTION
**Pull request by MoritzWeber0**
Dark blue was hard to read on some dark backgrounds. This commit changes all colors to bright colors.

### CODE REVIEW

**Review by romeonicholas — COMMENTED** [review]
This commit is obviously functionally fine, though if improving readability beyond this is something you'd like to see I could make a few suggestions (or just implement them and show you what I was thinking of).

**Comment by MoritzWeber0** [comment]
> This commit is obviously functionally fine, though if improving readability beyond this is something you'd like to see I could make a few suggestions (or just implement them and show you what I was thinking of).

If it doesn't take too long, go for it. If implementation would take too long, I'd appreciate if you quickly mention what it is about.

**Comment by romeonicholas** [comment]
I actually don't know what Collab Manager logs are currently used for outside of local development, but obviously I wouldn't want to break any current dependencies. Quick and messy, things I like in logs:

- High impact but limited coloring (I find it hard to read entire colored lines in general)
- Greater separation of fields with only essential descriptions (we know what timestamps are)
- Simpler date/time formats (again, only if you're not filtering on these somewhere it makes sense to use more code-friendly formats)

Ignore the transparency on my terminal, but this is a hastily coded example of the direction I'd go:
Log Example
```
def format(self, record):
        log_format = "%(asctime)s | %(name)s | %(funcName)s | %(message)s"
        date_format = "%Y-%m-%d | %H:%M:%S"

        if self.colored_output:
            level_format = (
                self._colors.get(record.levelno, "")
                + "%(levelname)s"
                + self._colors["reset"]
            )
        else:
            level_format = "%(levelname)s"

        complete_format = f"{level_format} {log_format}"

        formatter = logging.Formatter(complete_format, datefmt=date_format)
        return formatter.format(record)

class LogAdapter(logging.LoggerAdapter):
    def process(self, msg: str, kwargs):
        extra: dict = self.extra | kwargs.get("extra", {})

        client = extra.pop("client", "")
        user = extra.pop("user", "")
        method = extra.pop("method", "")
        path = extra.pop("path", "")
        trace_id = extra.pop("trace_id", "")

        msg = (
            f'{client} | user {user} {method}:{path} | "{msg}" | trace {trace_id}'
            + " ".join([f'{key}="{value}"' for key, value in extra.items()])
        )
        return (msg, kwargs)
```

**Comment by MoritzWeber0** [comment]
> I actually don't know what Collab Manager logs are currently used for outside of local development, but obviously I wouldn't want to break any current dependencies. Quick and messy, things I like in logs:
> 
> * High impact but limited coloring (I find it hard to read entire colored lines in general)
> * Greater separation of fields with only essential descriptions (we know what timestamps are)
> * Simpler date/time formats (again, only if you're not filtering on these somewhere it makes sense to use more code-friendly formats)
> 
> Ignore the transparency on my terminal, but this is a hastily coded example of the direction I'd go: Log Example
> 
> ```
> def format(self, record):
>         log_format = "%(asctime)s | %(name)s | %(funcName)s | %(message)s"
>         date_format = "%Y-%m-%d | %H:%M:%S"
> 
>         if self.colored_output:
>             level_format = (
>                 self._colors.get(record.levelno, "")
>                 + "%(levelname)s"
>                 + self._colors["reset"]
>             )
>         else:
>             level_format = "%(levelname)s"
> 
>         complete_format = f"{level_format} {log_format}"
> 
>         formatter = logging.Formatter(complete_format, datefmt=date_format)
>         return formatter.format(record)
> 
> class LogAdapter(logging.LoggerAdapter):
>     def process(self, msg: str, kwargs):
>         extra: dict = self.extra | kwargs.get("extra", {})
> 
>         client = extra.pop("client", "")
>         user = extra.pop("user", "")
>         method = extra.pop("method", "")
>         path = extra.pop("path", "")
>         trace_id = extra.pop("trace_id", "")
> 
>         msg = (
>             f'{client} | user {user} {method}:{path} | "{msg}" | trace {trace_id}'
>             + " ".join([f'{key}="{value}"' for key, value in extra.items()])
>         )
>         return (msg, kwargs)
> ```

Ah, it's about the actual format: The main source for reading logs should be Grafana Loki, which parses the provided strings. Therefore, we use the format that Grafana Loki uses. Only in the development environment we're reading the logs from the console.

Promtail / Grafana Loki reads from the files though, so we could change the log messages on the console to a better format. 

So fine for me, you can implement it for the console logger or open an issue for it :)

**Pull request merged**
